version: '3'
services:
  web:
    build:
      context: .
      target: build_as_root
    command: iex -S mix phx.server
    environment:
      DB_HOST: db
    links:
      - db
    ports:
      - 80:80
    volumes:
      - .:/app
    working_dir: /app
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sample_dev
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: